export function Hero() {
  return <section id="inicio" className="relative min-h-screen flex items-center overflow-hidden" style={{ background: "linear-gradient(145deg, #081D2C 0%, #0E2E46 55%, #0A2538 100%)" }} aria-label="Sección de inicio">
    <div className="geo-accent" style={{ width: 480, height: 480, background: "#55D6A9", top: -120, right: -80, opacity: 0.06 }} aria-hidden="true" /><div className="geo-accent" style={{ width: 260, height: 260, background: "#78BFEA", bottom: 80, left: -60, opacity: 0.08 }} aria-hidden="true" /><div className="absolute top-1/3 right-1/4 w-px h-40 opacity-10" style={{ background: "linear-gradient(to bottom, transparent, #78BFEA, transparent)" }} aria-hidden="true" /><div className="absolute bottom-1/4 left-1/3 w-24 h-px opacity-10" style={{ background: "linear-gradient(to right, transparent, #55D6A9, transparent)" }} aria-hidden="true" />
    <div className="max-w-6xl mx-auto px-5 pt-24 pb-16 w-full grid md:grid-cols-2 gap-12 items-center"><div>
      <span className="inline-flex items-center gap-2 text-xs font-semibold tracking-widest uppercase mb-6 px-3 py-1.5 rounded-full" style={{ color: "#55D6A9", background: "rgba(85,214,169,0.1)", border: "1px solid rgba(85,214,169,0.2)", fontFamily: "Sora, sans-serif" }}><span className="w-1.5 h-1.5 rounded-full" style={{ background: "#55D6A9" }} aria-hidden="true" />Odontología integral en Querétaro</span>
      <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight mb-5" style={{ color: "#F5F8FA", fontFamily: "Sora, sans-serif", letterSpacing: "-0.02em" }}>Tu sonrisa,<br /><span style={{ color: "#55D6A9" }}>en buenas</span><br />manos.</h1>
      <p className="text-base md:text-lg mb-8 leading-relaxed max-w-lg" style={{ color: "rgba(245,248,250,0.7)", fontFamily: "Inter, sans-serif" }}>Cuidamos tu salud dental con atención profesional, explicaciones claras y tratamientos pensados para ti y tu familia.</p>
      <div className="flex flex-col sm:flex-row gap-3 mb-10"><a href="#contacto" className="btn-primary px-7 py-3.5 text-sm text-center flex items-center justify-center gap-2" aria-label="Solicitar cita por WhatsApp"><svg width="18" height="18" fill="none" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.52 3.48A11.93 11.93 0 0 0 12 0C5.37 0 0 5.37 0 12c0 2.12.55 4.1 1.5 5.84L0 24l6.34-1.46A11.94 11.94 0 0 0 12 24c6.63 0 12-5.37 12-12 0-3.2-1.25-6.22-3.48-8.52z" fill="currentColor"/></svg>Solicitar cita</a><a href="#tratamientos" className="btn-outline px-7 py-3.5 text-sm text-center">Conocer tratamientos</a></div>
      <div className="flex flex-col sm:flex-row gap-5">{[{ icon: "👤", label: "Atención personalizada" }, { icon: "⚡", label: "Tecnología moderna" }, { icon: "👨‍👩‍👧", label: "Opciones para toda la familia" }].map((item) => <div key={item.label} className="flex items-center gap-2.5"><span className="flex items-center justify-center w-8 h-8 rounded-lg text-sm flex-shrink-0" style={{ background: "rgba(85,214,169,0.12)", border: "1px solid rgba(85,214,169,0.2)" }} aria-hidden="true">{item.icon}</span><span className="text-sm" style={{ color: "rgba(245,248,250,0.75)", fontFamily: "Inter, sans-serif" }}>{item.label}</span></div>)}</div>
    </div><div className="relative hidden md:block"><div className="rounded-2xl overflow-hidden aspect-[4/5] relative" style={{ boxShadow: "0 24px 64px rgba(0,0,0,0.4)" }}><img src="/images/hero-dental.jpg" alt="Equipo de odontólogos en atención profesional con paciente en clínica dental moderna" className="w-full h-full object-cover" loading="eager" /><div className="absolute inset-0" style={{ background: "linear-gradient(to top, rgba(8,29,44,0.5) 0%, transparent 60%)" }} aria-hidden="true" /></div><div className="absolute -bottom-4 -left-6 rounded-xl px-4 py-3 flex items-center gap-3" style={{ background: "rgba(14,46,70,0.95)", border: "1px solid rgba(120,191,234,0.2)", backdropFilter: "blur(12px)", boxShadow: "0 8px 24px rgba(0,0,0,0.3)" }}><span className="w-10 h-10 rounded-full flex items-center justify-center text-lg flex-shrink-0" style={{ background: "rgba(85,214,169,0.15)" }} aria-hidden="true">🦷</span><div><p className="text-white text-sm font-semibold" style={{ fontFamily: "Sora, sans-serif" }}>Atención integral</p><p className="text-xs" style={{ color: "rgba(245,248,250,0.55)", fontFamily: "Inter, sans-serif" }}>Adultos y niños · Querétaro</p></div></div></div></div>
    <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-1 opacity-40" aria-hidden="true"><span className="text-xs text-white" style={{ fontFamily: "Inter, sans-serif" }}>Descubre más</span><span className="text-white">⌄</span></div>
  </section>;
}
